### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by CsBigDataHub** [manatlan/reqman#9]
Thanks you for reqman.

I have been using this package for a few days now and I am impressed.

Only feedback I have have is that, documentation could be better. 

Let me know if I you need help with that, But first where are you generating the website from?

**Comment by manatlan** [comment]
thanks ...

Documentation is a real problem ;-)
Currently, it's hosted on glitch.com platform (because it's really easy, for me, to maintain that)
But IRL : I don't maintain it in real time ...

And currently : it's really really hot, coz I'm merging the reqman3 (lot of little changes) in master ... and I don't want any regressions ... So i'm really concentrated on that (with no times for doc)

I could need help ... for sure ....
perhaps I should put them on ghpages, like in the past/beginning (so others could send PR) ...
I really need to think about that

**Comment by manatlan** [comment]
hi @CsBigDataHub 

The docs are now in github : https://manatlan.github.io/reqman/
(generated by a github/action based on ~/docs/*.md and ~/mkdocs.yml)

It's better like that
